#!/usr/bin/env bash
# Displays "Best School" 10 times, saying "Hi" on the 9th iteration
count=1
while (( count <= 10 ))
do
    echo "Best School"
    if (( count == 9 ))
    then
        echo "Hi"
    fi
    ((count++))
done
