#!/usr/bin/env bash
# Loops from 1-10 with special messages for 4 and 8
n=1
while (( n <= 10 ))
do
    if (( n == 4 ))
    then
        echo "bad luck"
    elif (( n == 8 ))
    then
        echo "good luck"
    else
        echo "Best School"
    fi
    ((n++))
done
