#!/usr/bin/env bash
# Creates a PID file, handles signals, and loops indefinitely

trap 'echo "I hate the kill command"; rm -f /var/run/myscript.pid; exit' SIGTERM
trap 'rm -f /var/run/myscript.pid; exit' SIGQUIT
trap 'echo "Y U no love me?!"' SIGINT

echo $$ > /var/run/myscript.pid

while true
do
    echo "To infinity and beyond"
    sleep 2
done
